export const initialState = {
  products: {
    data: [
      {
        id: '1',
        name: 'Banana & coconut yellow sponge cake',
        description: 'Classic sponge cake with banana flavor and cream fillings: Coconut & Vanilla. Cake is decorated with white chocolate mousse & crème fraîche.',
        size:'8" for 16 to 20 guests',
        price: 80,
        imageMain: '/images/coconut_cake.jpg',
        alt: 'Coconut cake',
        imageSm1: '/images/coconut_cake1.jpg',
        imageSm2: '/images/coconut_cake2.jpg',
        imageSm3: '/images/coconut_cake3.jpg',
      },
      {
        id: '2',
        name: 'Chocolate muffins',
        description: 'Chocolate muffins filled with walnut cream, incredibly moist and fluffy, rich in chocolate flavour, stuffed full of chocolate chips.',
        size:'pcs',
        price: 2.50,
        imageMain: '/images/muffins.jpg',
        alt: 'Muffins',
        imageSm1: '/images/muffins1.jpg',
        imageSm2: '/images/muffins2.jpg',
        imageSm3: '/images/muffins3.jpg',
      },
      {
        id: '3',
        name: 'Yellow or chocolate cupcakes',
        description: 'Classic yellow or chocolate cupcakes. Not stuffed. Decorated with flavored cream: chocolate/coconut/vanilla/walnut. Gluten free also available!',
        size:'pcs',
        price: 2.50,
        imageMain: '/images/cupcakes.jpg',
        alt: 'Cupcakes',
        imageSm1: '/images/cupcakes.jpg',
        imageSm2: '/images/cupcakes.jpg',
        imageSm3: '/images/cupcakes.jpg',
      },
      {
        id: '4',
        name: 'Chocolate & salted caramel anniversary cake',
        description: 'Anniversary cake with chocolate & walnut flavor. 2 cream fillings: Dark Chocolate Mousse & Hazelnut. Cake is decorated with Salted Caramel cream & Dark Chocolate icing. Milk Chocolate Mousse puff on top. Cake with fresh raspberries on top is available.',
        size:'8" for 16 to 20 guests',
        price: 95,
        imageMain: '/images/salted_caramel_cake.jpg',
        alt: 'Salted caramel cake',
        imageSm1: '/images/salted_caramel_cake.jpg',
        imageSm2: '/images/salted_caramel_cake.jpg',
        imageSm3: '/images/salted_caramel_cake.jpg',
      },
      {
        id: '5',
        name: 'Classic Chocolate cake',
        description: 'Classic Chocolate cake  with 2 cream fillings: Dark Chocolate Mousse & Caramel cream. It’s decorated with Chocolate Peanut Butter Mousse & Chocolate truffles on top.',
        size:'8" for 16 to 20 guests',
        price: 85,
        imageMain: '/images/chocolate_caramel_cake.jpg',
        alt: 'Chocolate cake',
        imageSm1: '/images/chocolate_caramel_cake.jpg',
        imageSm2: '/images/chocolate_caramel_cake.jpg',
        imageSm3: '/images/chocolate_caramel_cake.jpg',
      },
      {
        id: '6',
        name: 'Pistachio puff pastry layer cake',
        description: 'Puff pastry layer cake with delicate banana flavor addition. 2 cream fillings: Pistachio & Lime flavor. Decorated with Caramel Crème Brûlée icing & slices of key lime.',
        size:'8" for 16 to 20 guests',
        price: 75,
        imageMain: '/images/pistachio_cake.jpg',
        alt: 'Pistachio cake',
        imageSm1: '/images/pistachio_cake.jpg',
        imageSm2: '/images/pistachio_cake.jpg',
        imageSm3: '/images/pistachio_cake.jpg',
      },
      {
        id: '7',
        name: 'Amazing raspberry wedding cake',
        description: 'Raspberry wedding cake with cream fillings: Vanilla, Honey & Coconut flavor. Covered with raspberry sugar paste & fresh flowers.',
        size:'8" for 16 to 20 guests',
        price: 450,
        imageMain: '/images/raspberry_wedding_cake.jpg',
        alt: 'Raspberry wedding cake',
        imageSm1: '/images/raspberry_wedding_cake.jpg',
        imageSm2: '/images/raspberry_wedding_cake.jpg',
        imageSm3: '/images/raspberry_wedding_cake.jpg',
      },
      {
        id: '8',
        name: 'Classic sponge Banana & White chocolate cake',
        description: 'Classic yellow sponge cake with banana flavor. Cream fillings: White Chocolate Mousse. Decorated with crème fraîche & cherries out of liqueur.',
        size:'8" for 16 to 20 guests',
        price: 83,
        imageMain: '/images/banana_cake.jpg',
        alt: 'Banana cake',
        imageSm1: '/images/banana_cake.jpg',
        imageSm2: '/images/banana_cake.jpg',
        imageSm3: '/images/banana_cake.jpg',
      },
      {
        id: '9',
        name: 'Macaroons',
        description: 'Traditional French pastries, butter-creamed filled cookie sandwiches. Flavors: strawberry, lemon, vanilla, honey, caramel, coffee, mint. Sold from min 6 pcs. Choose flavor or ‘mixed’ option – a box of assorted macaroons.',
        size:'-',
        price: 2.50,
        imageMain: '/images/macaroons.jpg',
        alt: 'Macaroons',
        imageSm1: '/images/macaroons.jpg',
        imageSm2: '/images/macaroons.jpg',
        imageSm3: '/images/macaroons.jpg',
      },
      {
        id: '10',
        name: 'Carrot Cake',
        description: 'Carrot cake with 2 cream fillings: crème fraîche & caramel. Decorated with crème fraîche & crumble topping. Decoration with lovely sugar bees on top is available.',
        size:'8" for 16 to 20 guests',
        price: 70,
        imageMain: '/images/carrot_cake.jpg',
        alt: 'Carrot cake',
        imageSm1: '/images/carrot_cake.jpg',
        imageSm2: '/images/carrot_cake.jpg',
        imageSm3: '/images/carrot_cake.jpg',
      },
    ],
    loading: {
      active: false,
      error: false,
    },
  },

  categories: [
    { id: '1', name: 'Birthday Cakes' },
    { id: '2', name: 'Children’s Birthday Cakes' },
    { id: '3', name: 'Seasonal Cakes' },
    { id: '4', name: 'Wedding Cakes' },
    { id: '5', name: 'Decorated Cookies and Cupcakes' },
    { id: '6', name: 'Muffins' },
    { id: '7', name: 'Desserts' },
  ],

};